name: Build and run

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: 1.52.1
        components: rustfmt,clippy
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Generate build
      run: cargo build --release
    - name: Generate doc
      run: cargo doc --no-deps
    - name: Run all days
      run: cargo run --release -- run-all
