name: Check lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: 1.52.1
        components: rustfmt,clippy
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --tests --all-features -- -D warnings
